name: Terraform Plan

on:
  workflow_dispatch:   # manual trigger
  pull_request:        # run on PRs
    paths:
      - 'terraform/EKS/**'
      - 'terraform/k8s/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: [terraform/EKS, terraform/k8s]  # Add more dirs as needed

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
