name: Terraform Plan

on:
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      eks: ${{ steps.filter.outputs.eks }}
      k8s: ${{ steps.filter.outputs.k8s }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            eks:
              - 'terraform/EKS/**'
            k8s:
              - 'terraform/k8s/**'

  terraform:
    needs: changes
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dir: EKS
            run: ${{ needs.changes.outputs.eks }}
          - dir: k8s
            run: ${{ needs.changes.outputs.k8s }}

    if: matrix.run == 'true'

    defaults:
      run:
        working-directory: terraform/${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out=tfplan
