name: Terraform Deploy to AWS

on:
  workflow_dispatch:  # allows manual triggering
  push:
    branches:
      - feature/EKS-IAC  # adjust if you want to trigger on a different branch

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/EKS  # adjust if your Terraform files are elsewhere

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # use the version you prefer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # update to your region

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # only apply on main branch
        run: terraform apply -auto-approve tfplan
